version: '3.4'

services:
  blazorhero:
    image: renter-manager-app
    build:
      context: .
      dockerfile: src/Server/Dockerfile
    environment:
      - "ConnectionStrings__DefaultConnection=Server=db;Data Source=192.168.1.8,1433;Initial Catalog=RenterManager;User ID=sa;Password=Peter@123;TrustServerCertificate=True"
      - "ASPNETCORE_Kestrel__Certificates__Default__Password=securePassword123"
      - "ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx"
    volumes:
      - ~/.aspnet/https:/https:ro
    ports:
      - "5005:5005"
      - "5006:5006"
    depends_on:
      - db
    restart: on-failure
    container_name: renter-manager-app

  db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
      - "SA_PASSWORD=Peter@123"
      - "ACCEPT_EULA=Y"
    container_name: mssql